# Generated by Django 5.2.4 on 2025-07-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Jueves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Lunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Martes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Miercoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Sabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Viernes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('nombre_programa', models.CharField(max_length=200, verbose_name='Nombre del programa')),
            ],
        ),
    ]
